# Generated by Django 4.1.2 on 2022-11-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='主机名')),
                ('private_ip', models.GenericIPAddressField(verbose_name='内网Ip')),
                ('mac_address', models.CharField(max_length=100, unique=True, verbose_name='Mac地址')),
                ('cpu', models.IntegerField(verbose_name='CPU')),
                ('disk', models.CharField(max_length=50, verbose_name='磁盘')),
                ('manufacturers', models.CharField(max_length=100, verbose_name='制造商')),
                ('server_type', models.CharField(max_length=32, verbose_name='服务器类型')),
                ('st', models.CharField(max_length=100, verbose_name='序列号')),
                ('uuid', models.CharField(max_length=100, verbose_name='UUID')),
                ('manufacturer_date', models.CharField(max_length=100, verbose_name='生产日期')),
                ('os', models.CharField(max_length=100, verbose_name='操作系统')),
                ('vm_status', models.IntegerField(choices=[(0, '在线'), (1, '下线'), (2, '空闲')], verbose_name='服务器状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'db_table': 'assets',
            },
        ),
    ]
